Finished the homework 8
MaximIurceac/MAXIM_IURCEAC pull request #9
Opened 2023-04-21 12:34 UTC by MaximIurceac

Please check my hw

2023-04-23 11:51 UTC, gh3rtzz commented on src/main/java/org/example/homework_nr_8/Animal.java
> +    default void drink(){
add a simple implementation here. If you want it to do nothing, make it print out to console that it's not overriden.

2023-04-24 15:02 UTC, MaximIurceac commented
I added the implementation

2023-04-24 17:58 UTC, gh3rtzz commented on src/main/java/org/example/homework_nr_8/Elephant.java
> +        Animal.super.drink();
Clever, but, it voids the usage of the default methods in interfaces.

Picture this:

You have a default method in an interface. By interface rules default method must have a body
One more rule is that default methods do not have to be overriden if we compare them to abstract methods.
Therefore, if you override the default method and then call super of the interface and call the default method, it doesn't make sense.

When you override it here, create a new implementation.
ex. `@Override
public void drink(){
System.out.println("Elephant is drinking");`

2023-04-24 17:58 UTC, gh3rtzz commented on src/main/java/org/example/homework_nr_8/Elephant.java
> +        System.out.println("Erbivor is sleeping");
Why is it erbivor? You're overriding this method inside the Elephant class and not Erbivor

2023-04-24 21:57 UTC, MaximIurceac commented
Tell me pls. It will be right if I delete the method "drink" in Elephant class and left the method in interface "Animal"?
I watched the leasson again and you are right that the point of default class is lost.

2023-04-26 18:18 UTC, gh3rtzz requested changes
Use the default method drink() somewhere

2023-04-27 09:55 UTC, MaximIurceac commented on src/main/java/org/example/homework_nr_8/Elephant.java
> +        elephant.drink();
I'm using it here

2023-04-28 17:47 UTC, gh3rtzz approved these changes
approved

2023-04-28 18:24 UTC, merged